export const INIT = 'INIT';
export const EXPAND_COLLAPSE_NODE = 'EXPAND_COLLAPSE_NODE';
export const CREATE_NODE = 'CREATE_NODE';

export const FETCH_SITE = 'FETCH_SITE';
export const FETCH_SITE_PENDING = 'FETCH_SITE_PENDING';
export const FETCH_SITE_FULFILLED = 'FETCH_SITE_FULFILLED';
export const FETCH_SITE_REJECTED = 'FETCH_SITE_REJECTED';

export const FETCH_WEB = 'FETCH_WEB';
export const FETCH_WEB_PENDING = 'FETCH_WEB_PENDING';
export const FETCH_WEB_FULFILLED = 'FETCH_WEB_FULFILLED';
export const FETCH_WEB_REJECTED = 'FETCH_WEB_REJECTED';

export const EXPAND_WEB = 'EXPAND_WEB';
export const EXPAND_WEB_FULFILLED = 'EXPAND_WEB_FULFILLED';

export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_LIST_PENDING = 'FETCH_LIST_PENDING';
export const FETCH_LIST_FULFILLED = 'FETCH_LIST_FULFILLED';
export const FETCH_LIST_REJECTED = 'FETCH_LIST_REJECTED';