export enum NODE_TYPE {
    TENANT,
    SITE,
    WEB,
    WEBS,
    LIST,
    LISTS,
    FIELD,
    VIEW,

    WEB_ALERTS,
    WEB_ALLPROPERTIES,
    WEB_CONTENTTYPES,
    WEB_EVENTRECEIVERS,
    WEB_FEATURES,
    WEB_FIELDS,
    WEB_GROUPS,
    WEB_LISTTEMPLATES,
    WEB_PROPERTIES,
    WEB_ROOTFOLDER,
    WEB_USERS,
    WEB_SOLUTIONS
}